# permissions for end users to edit netscalerobservabilityexporters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: netscalerobservabilityexporter-editor-role
rules:
- apiGroups:
  - netscaler.com
  resources:
  - netscalerobservabilityexporters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - netscaler.com
  resources:
  - netscalerobservabilityexporters/status
  verbs:
  - get
