# permissions for end users to view netscalerobservabilityexporters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: netscalerobservabilityexporter-viewer-role
rules:
- apiGroups:
  - netscaler.com
  resources:
  - netscalerobservabilityexporters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - netscaler.com
  resources:
  - netscalerobservabilityexporters/status
  verbs:
  - get
